(import (srfi :64))
(import (sse utils))
(import (tests ploc))
(import (tests bounds))

(for-each (lambda (n)
            (for-each (lambda (d-max)
                        (let* ((B (<< 1 d-max))
                               (V (inexact->exact (ceiling (sqrt B))))
                               (c (get-min-c* 128 n d-max)))
                          (define name (format #f "ploc, n=~a, B=~a" n B))
                          (test-begin name)
                          (test-assert (test-ploc n B V c))
                          (test-end name)))
                      (list 10 16 20)))
          (list 16 64 256))
